### ISSUE TITLE
좋아요가 나 혼자서 17개씩 찍힌다. 

### ISSUE THREAD

**Issue by favorsyoon** [8Avengers/YumYum-BE#123]
![image](https://user-images.githubusercontent.com/114038409/226117639-6c4f587c-17d7-4397-9759-42ca9cb35726.png)

like를 눌렀을 때, 
어떤 거는 좋아요가 끝도 없이 올라간다. 
껐다 키는 방식이 이날 켜져 있으면 켜

꺼져 있으면 켜지는 요청
켜져 있으면 꺼지는 요청 
팔로우는 요청 하나인데, 

좋아요는 두개로 나눴다
만약에 데이터가 고정값으로 들어오면 변하지 않으면, 한 요청밖에 하지 못한다. 

좋아요가 혼자서 17개씩 찍힌다. 

뉴스피드에서는 그런 오류가 안발생하는데, 
프로필 페이지에서 발생한다. 

상대 프로필 페이지 좋아요 버그 ? (본인 프로필 x ) 
(상대 프로필페이지 좋아요 조회 한번 확인 가능하신가용?)

=> 팔로우 팔로잉 처럼 한번 누르면 좋아요, 두번 누르면 좋아요 취소 처럼 바꿔보자.

**Comment by sayapin1** [comment]
흠... 좋아요 하는 기능은 뉴스피드나 프로필쪽과는 별개의 api라서 오류가 난다면 둘 다 나야 하는데 프로필쪽에서만 난다는 게 이상하네요. 프로필페이지의 좋아요api 연결에 문제가 있는 거 아닐까요?

**Comment by favorsyoon** [comment]
![image](https://user-images.githubusercontent.com/114038409/226176655-30d74cc1-7740-40ae-845d-ba418ddda7ef.png)
좋아요 취소 API 연결 부탁드립니다. :)

**Comment by sayapin1** [comment]
해결안되지 않았나요? 배포를 아직 안하셔서 그런 걸 수도 있지만, 현재로써는 문제가 해결되지 않은 것으로 보입니다.

**Comment by sayapin1** [comment]
배포 후 이슈 해결된 걸로 확인하여서 닫겠습니다.
