### ISSUE TITLE
Post 수정 

### ISSUE THREAD

**Issue by favorsyoon** [8Avengers/YumYum-BE#129]
- [x] 포스트 수정 시에 장소가 바뀌어 버림 (장소를 수정하지 않았음에도 장소가 변경)
- [ ] 포스트 수정 시에 동일한 포스트가 collection에 등록 (ex : 게시글 1을 3번 수정하면 해당 collection에 [게시글1,게시글1,게시글1])

**Comment by sayapin1** [comment]
1번 오류는 121번 이슈로 이미 열어놨습니다. 지워주세요.

**Comment by favorsyoon** [comment]
> 1번 오류는 121번 이슈로 이미 열어놨습니다. 지워주셔도 될 것 같아요.

감사합니다!
