### ISSUE TITLE
[Fix] createPost 할 때 마이리스트에도 들어가는 쿼리문 오류

### ISSUE THREAD

**Issue by sayapin1** [8Avengers/YumYum-BE#14]

**Comment by sayapin1** [comment]
버그가 아니라 컬렉션db에 데이터가 없어서 생기는 문제였어서 이슈 닫도록 하겠습니다. 추후에 정훈님께서 마이리스트에 포스트 추가할 때에 받은 마이리스트id가 db에 없을 경우 notFoundException을 throw하도록 코드를 수정해주시면 될 것 같습니다.

**Comment by favorsyoon** [comment]
좋습니다
@sayapin1 @pyoja
