### ISSUE TITLE
 Fix :  my-list 수정사항 컬렉션당 게시물 제한 및 나의 리스트 배열로 포스팅

### ISSUE THREAD

**Issue by favorsyoon** [8Avengers/YumYum-BE#16]
- [ ] 컬렉션당 게시물 3개로 제한 

나의 맛집리스트 전체보기 PAGE 1페이지에서 
최근 추가한 게시물 3개만 보여주세요. 

![image](https://user-images.githubusercontent.com/114038409/224525512-333d10a0-5982-4536-bb1c-cc261c8ffdc3.png)

문제의 원인 : 5개(또는 그 이상) X 마이리스트10개 조회시 총 게시물 50개 조회라서 로딩시간이 너무 많이 걸립니다.

TODO:
인기 조회 : 
게시물 조회 순으로 정렬 
게시물 좋아요 순으로 정렬 하면됩니다.

- [ ]  포스팅작성시 나의 리스트들이 배열로 됩니다.
![image](https://user-images.githubusercontent.com/114038409/224525769-e1f9a7fe-44db-4d82-b3df-15aded98fa1b.png)

**Comment by pyoja** [comment]
현재는 최신게시물 순으로 정리됩니다.
예를 들어 1,2,3,4 포스팅을 저장했다면 4,3,2 까지 가져옵니다.
