### ISSUE TITLE
[Fix] : restful API 만들기 프로필/팔로우/팔로잉 요청 월요일아침까지

### ISSUE THREAD

**Issue by favorsyoon** [8Avengers/YumYum-BE#28]
다른 사람 프로필 불러오기
METHOD : Get
www.yumyumdb.net/profile/:userId

나의프로필페이지불러오기
METHOD : Get
www.yumyumdb.net/profile/me

나의 프로필 수정하기
METHOD : Put
www.yumyumdb.net/profile/me

나의 프로필 삭제하기= 회원탈퇴 
METHOD : Delete
www.yumyumdb.net/profile/me

유저팔로우하기 
METHOD: Post
www.yumyumdb.net/profile/:userId/follow

 유저팔로우취소하기  
METHOD: Delete
www.yumyumdb.net/profile/:userId/follow

 유저의 팔로워 불러오기
Method: Get
www.yumyumdb.net/profile/:userId/followers

유저의 팔로잉 불러오기
Method: Get
www.yumyumdb.net/profile/:userId/followings

**Comment by favorsyoon** [comment]
아직 미완성

**Comment by hansejun** [comment]
좋습니다!!!

**Comment by favorsyoon** [comment]
API에 반영했습니다.

https://plucky-summer-2c4.notion.site/1d8ca1a3eaad4f19b66bef99ab38e342?v=0445a1b8df1a42709e78c9627653239b

부족한 부분은 언제든지 말씀해주세요!
감사합니다.
