### ISSUE TITLE
[Fix] : 탈퇴한 회원이 가입했던 이메일로 재가입하는 경우 예외처리 

### ISSUE THREAD

**Issue by favorsyoon** [8Avengers/YumYum-BE#40]
음..? 일단은 이미지부터 끝내자

**Comment by sayapin1** [comment]
그럼 탈퇴시에 softdelete를 하지않고 그냥 delete를 해서 모든 정보를 폐기하면 되지 않을까요

**Comment by favorsyoon** [comment]
> Member

**Comment by favorsyoon** [comment]
고객님들이 나중에 계정살려달라고 할 수도 있고, 데이터는 우리회사의 귀중한 자산입니다. 폐기하면 안됩니다.

**Comment by favorsyoon** [comment]
쉽게 못나가지 이 이슈는 #46 으로 옮겼습니다. 감사합니다. 드레보리님

**Comment by favorsyoon** [comment]
#46 으로 오셔서 많이 도와주세요. 대단히 감사합니다.
