### ISSUE TITLE
회원 한명 탈주하면 그 회원과 관계를 맺고 있는 모든 게시물, 팔로잉 팔로워 좋아요 다 난리가 난다.

### ISSUE THREAD

**Issue by favorsyoon** [8Avengers/YumYum-BE#56]
![image](https://user-images.githubusercontent.com/114038409/224930963-d4e6889a-f713-46a3-bd54-b8cfca441150.png)

원인: typeorm soft delete

서비스:

회원탈퇴시 그 회원이 작성한 게시글, 좋아요, 리스트 등등 회원과 관계를 맺고 있던 모든 데이터를 바로 삭제 해버리면 회사 차원에서 손해이지 않을까? 

회원이 실수로 탈퇴해서 고객센터에 전화해서 회원계정 다시 살려달라고 요청할수도 있다.

최대한 회원의 데이터를 DB에 저장해놓자. 탈퇴후 몇 년후 지우는 방향으로 바꾸자. 

기술:

deleted_at null 이 아니면 문제가 이런 문제가 생긴다. 
블로그에서 본 것 같다. 찾압자

**Comment by pyoja** [comment]
헉

**Comment by sayapin1** [comment]
1. 내 포스트를 좋아요한 사람이 탈퇴할 경우 문제가 없는지
2. 유저가 탈퇴할 경우 그 사람의 포스트는 볼 수 있지만 유저 정보가 null값으로 들어오는데 어떻게 해야하는지.

**Comment by favorsyoon** [comment]
이렇게 소프트딜리트 전에는 팔로워 목록이 나오다가 

![image](https://user-images.githubusercontent.com/114038409/226099961-eea8dac2-302e-4681-8f2e-9dd78e5650d2.png)



소프트딜리트 하면 
![image](https://user-images.githubusercontent.com/114038409/226100059-104913a3-266a-4629-af07-68afd48e9e82.png)
팔로워 목록 전체가 위 사진처럼 나오지 않는다.


소프트딜리트 완료후 


소프트딜리트한 사람의 뉴스피드 
소프트딜리트된 사람은 피드에 아래와 같이 노출된다. 
![image](https://user-images.githubusercontent.com/114038409/226100033-ded1e0cd-9ed9-4125-9f5a-f3175b478e86.png)



##소프트딜리트한 사람의 댓글
![image](https://user-images.githubusercontent.com/114038409/226100046-c15a838e-7d7d-4dc2-9fd5-655a5b31923c.png)


![image](https://user-images.githubusercontent.com/114038409/226100145-b7417346-3ad9-4cf4-988a-2934110d5aa2.png)

댓글은 나오는데,  이미지가 깨져서 나온다.

**Comment by favorsyoon** [comment]
삭제된 사람은 안나와야 한다
