### ISSUE TITLE
[FIX] : 포스트 수정시에 마이리스트를 변경할 경우 원래있던 마이리스트에 포스팅은 삭제되는 기능

### ISSUE THREAD

**Issue by sayapin1** [8Avengers/YumYum-BE#76]
에 대해서 같이 고민해봐야할 것 같아요.

설명: 포스트 수정시에 마이리스트를 변경할 경우(원래 들어가있던 마이리스트를 선택 해제하고 다른 마이리스트를 선택할 경우) 원래 들어가있던 마이리스트에서는 포스트가 빠지도록 하는 기능이 필요할 것 같습니다.

**Comment by pyoja** [comment]
MyList 포스팅 업데이트라는 이름으로 함수를 만들어보고 있긴한데,
Put을 사용해서 collection 아이디값만 변경하는 것까진 되겠지만
선택해제한 컬렉션값을 삭제하는 기능을 어떻게 해야할지 감이 안오네요.
