### ISSUE TITLE
[Fix] : 그 사람의 게시물이 없을 때, 에러처리 하지말고, [] 로 응답해주세요. 

### ISSUE THREAD

**Issue by favorsyoon** [8Avengers/YumYum-BE#91]
그 사람의 게시물이 없을 때, 에러처리 하지말고, [] 로 응답해주세요.  에러만 안뜨게
![image](https://user-images.githubusercontent.com/114038409/225348960-97685f8f-9cab-48a6-8f7e-cbae541df332.png)

**Comment by sayapin1** [comment]
완료
