### ISSUE TITLE
[Fix] : 나의 맛집리스트 타이틀만 불러오기(나의 맛집 선택창)

### ISSUE THREAD

**Issue by favorsyoon** [8Avengers/YumYum-BE#97]
### 원인
response Body에  id를 return 하지 않아서 생긴 문제입니다. 

![image](https://user-images.githubusercontent.com/114038409/225401392-825a180a-f08e-4dce-afae-e116b90438f7.png)

맛집 1 
맛집 1
맛집 1 
이렇게 있으면, name만 console.log에 찍히기 때문에 
id값이 없어서 프론트에서 어떤 id 값 1이 맛집 1인지 id 값 2가 맛집 1인지 id값3이 맛집 1인지 모르겠습니다.
프론트에서 어떤 맛집 1 의 API를 보내줘야할지 모르게 됩니다.

![image](https://user-images.githubusercontent.com/114038409/225400338-e9ab0ca1-62da-4125-85c6-f327d9379dfe.png)

![image](https://user-images.githubusercontent.com/114038409/225400805-ffa8aa6a-7552-4136-981e-edfd1c80ffc5.png)

###해결책 

나의 맛집리스트 타이틀만 불러오기
response 리턴값이 name밖에 없다. 
id값이 없다. id를 추가부탁드립니다. 

response 할 때 기본적으로 id값을 넣어주시면 프론트에서 아주 좋다고 합니다!
프론트에서 찾기가 아주 편안해 진다고 합니다!

response에 id값도 추가해서 return 부탁드립니다 👍 
감사합니다!

**Comment by pyoja** [comment]
ID값도 추가하였습니다.
